name: petadopt
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  quiver: '>=2.0.5'
  cupertino_icons: ^0.1.0
  location: ^3.0.2
  url_launcher: ^3.0.1
  shared_preferences: ^0.4.1
  collection: ^1.14.6
  protobuf: ^0.9.0
  geocoder: ^0.2.1
  photo_view: ^0.9.2
  http: ^0.12.0+4
  sqflite: ^1.3.0
  cached_network_image: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

module:
  androidX: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/app_white_icon.png
   - assets/app_black_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster 
      fonts:
          - asset: fonts/Lobster-Regular.ttf
    - family: LobsterTwo 
      fonts:
          - asset: fonts/LobsterTwo-Regular.ttf
    - family: OpenSans 
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic
    - family: Raleway 
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic 

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
